Create reviews
JulianBaxandall/The-Sand-Review pull request #12
Opened 2022-08-09 18:27 UTC by Bryan-Genest

1. User can add review to beach show page
2. Index page has links to beaches show page
3. Beach and Reviews now serializes, one fetch for Beach show page
4. Review json tests (structure of response)
5. Refactored ReviewShowTile.js, moved in logic from parent file BeachesShow.js

2022-08-09 19:02 UTC, nwalberts requested changes

2022-08-09 19:02 UTC, nwalberts commented on config/routes.rb
> +        resources :reviews, only: [:index, :create]
remove index

2022-08-09 19:02 UTC, nwalberts commented on db/seeds.rb
> +            text: "This is a bad review",
i know its annoying, but can we have slightly more real review text?

2022-08-09 19:02 UTC, nwalberts commented on db/seeds.rb
> +admin1 = User.create!({:email => "myemail@gmail.com", :role => "admin", :password => "111111", :password_confirmation => "111111" })
we should not use hashrocket syntax. use the syntax from the rest of the seed file!

2022-08-09 19:02 UTC, nwalberts commented on spec/features/user_creates_new_review.rb
> +
we need a test for the sad path as well!

2022-08-09 20:00 UTC, JulianBaxandall commented on db/seeds.rb
> +            text: "This is a bad review",
-This is a bad review of this suggestion-

2022-08-09 20:51 UTC, closed without merging

2022-08-12 01:52 UTC, Bryan-Genest commented
Why does git say this has unmerged changes 🧐🧐